#! /usr/bin/env bash

echo "Enabling elastic stack containers..."
if [[ $(grep "container_name: kibana" docker-compose.yml -c) == "0" ]]
then
  cat compose-files/elastic-stack.yml >> docker-compose.yml
fi
